openapi: 3.0.0
info:
  title: OOUI-memo
  version: '1.0'
  description: OOUIワークアウト - メモアプリケーション API仕様書
  contact: {}
servers:
  - url: 'http://localhost:3101'
    description: ''
paths:
  /memos:
    get:
      summary: GET Memos
      tags:
        - Memos
      responses:
        '200':
          $ref: '#/components/responses/memos'
        '500':
          $ref: '#/components/responses/error'
      operationId: get-memos
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      description: メモ一覧参照API
    post:
      summary: POST Memo
      operationId: post-memos
      responses:
        '201':
          description: Created
        '500':
          $ref: '#/components/responses/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
            examples: {}
      description: メモ作成API
      tags:
        - Memos
  '/memos/{memo_id}':
    parameters:
      - $ref: '#/components/parameters/memo_id'
    get:
      summary: GET Memo
      tags:
        - Memos
      responses:
        '200':
          $ref: '#/components/responses/memo'
        '404':
          $ref: '#/components/responses/error'
        '500':
          $ref: '#/components/responses/error'
      operationId: get-memo
      description: メモ詳細参照API
    put:
      summary: PUT Memo
      operationId: put-memo
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/error'
        '500':
          $ref: '#/components/responses/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
      description: メモ編集API
      tags:
        - Memos
    delete:
      summary: DELETE Memo
      operationId: delete-memo
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/error'
        '500':
          $ref: '#/components/responses/error'
      description: メモ削除API
      tags:
        - Memos
components:
  schemas:
    Memo:
      $ref: ./models/memo.v1.json
    Error:
      $ref: ./models/error.v1.json
  responses:
    memos:
      description: メモ一覧参照レスポンス
      content:
        application/json:
          schema:
            type: array
            description: メモ情報の配列（※title、content は先頭30文字分のみ取得）
            items:
              $ref: '#/components/schemas/Memo'
          examples: {}
    memo:
      description: メモ詳細参照レスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Memo'
    error:
      description: エラーレスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            '404':
              value:
                message: リクエストされたリソースが見つかりませんでした。リソース識別子をご確認ください。
            '500':
              value:
                message: システムエラーが発生しました。恐れ入りますが再度やり直してください。
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      description: レコード取得件数
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
      description: レコード取得開始位置
    memo_id:
      name: memo_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: メモID
tags:
  - name: Memos
  - name: Users
