openapi: 3.0.0
info:
  title: OOUI-memo
  version: '1.0'
  description: OOUIワークアウト - メモアプリケーション API仕様書
  contact: {}
servers:
  - url: 'http://localhost:3101'
    description: ''
paths:
  /memos:
    get:
      summary: GET Memos
      tags:
        - Memos
      responses:
        '200':
          $ref: '#/components/responses/Memos'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
      operationId: get-memos
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
        - $ref: '#/components/parameters/page'
      description: メモ一覧取得API
    post:
      summary: POST Memo
      operationId: post-memos
      responses:
        '201':
          description: Created
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/ServerError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
            examples: {}
      description: メモ作成API
      tags:
        - Memos
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
  '/memos/{memo_id}':
    parameters:
      - $ref: '#/components/parameters/memo_id'
    get:
      summary: GET Memo
      tags:
        - Memos
      responses:
        '200':
          $ref: '#/components/responses/Memo'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
      operationId: get-memo
      description: メモ詳細取得API
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
    put:
      summary: PUT Memo
      operationId: put-memo
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/ServerError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Memo'
            examples: {}
      description: メモ編集API
      tags:
        - Memos
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
    delete:
      summary: DELETE Memo
      operationId: delete-memo
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/ServerError'
      description: メモ削除API
      tags:
        - Memos
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
  /login:
    post:
      summary: Login
      operationId: login
      responses:
        '200':
          $ref: '#/components/responses/User'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
            examples:
              example-1:
                value:
                  email: dummy@email.com
                  password: test3101
      description: ログインAPI
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
  /logout:
    post:
      summary: Logout
      operationId: logout
      responses:
        '200':
          description: OK
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - Auth
      description: ログアウトAPI
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
  /user:
    get:
      summary: GET User
      tags:
        - Users
      responses:
        '200':
          $ref: '#/components/responses/User'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
      operationId: get-user
      description: ログインユーザ取得API
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
  /register:
    post:
      summary: POST User
      operationId: user-register
      responses:
        '201':
          $ref: '#/components/responses/User'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/ServerError'
      description: ユーザ新規登録API
      parameters:
        - $ref: '#/components/parameters/XSRF-TOKEN'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      tags:
        - Auth
        - Users
components:
  schemas:
    Memo:
      $ref: ./models/memo.v1.json
    Error:
      $ref: ./models/error.v1.json
    User:
      $ref: ./models/user.v1.json
    UserLogin:
      $ref: ./models/user-login.v1.json
  responses:
    Memos:
      description: メモ一覧情報レスポンス
      content:
        application/json:
          schema:
            type: array
            description: メモ情報の配列（※title、content は先頭30文字分のみ取得）
            items:
              $ref: '#/components/schemas/Memo'
          examples: {}
    Memo:
      description: メモ詳細情報レスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Memo'
    User:
      description: ユーザ情報レスポンス
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    ValidationError:
      description: |-
        UNPROCESSABLE_ENTITY：422
        バリデーションエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            '422':
              value:
                message: The given data was invalid.
                errors:
                  email: ログインできません。入力した情報に誤りがないかご確認ください。
    ServerError:
      description: |-
        INTERNAL_SERVER_ERROR：500
        サーバエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            '500':
              value:
                message: Server Error
    UnAuthorizedError:
      description: |-
        UNAUTHORIZED：401
        認証エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            '401':
              value:
                message: Unauthenticated.
    NotFoundError:
      description: |-
        NOT_FOUND：404
        リソースが見つからないエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    memo_id:
      name: memo_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: メモID
    XSRF-TOKEN:
      name: XSRF-TOKEN
      in: cookie
      required: true
      schema:
        type: string
      description: CSRF対策
    page:
      name: page
      in: query
      required: false
      schema:
        type: number
      description: ページ数
  securitySchemes: {}
tags:
  - name: Memos
  - name: Users
  - name: Auth
